<a href="https://colab.research.google.com/github/nausahadali/Python-Basic-to-Advance/blob/main/AI_ML_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loops

Question 1. Print all the Prime numbers between 1 to N.

In [ ]:
num = int(input("Enter the value of N:-  \n"))
for n in range(2, num + 1):
  for i in range(2, n):
    if n % i == 0:
      break
  else:
    print(n)



Enter the value of N:-  
10
2
3
5
7


Question 2 Print the sum of all prime number between A to B.


In [ ]:
a = int(input("Enter the value of A. "))
b = int(input("Enter the value of B."))
sum = 0
for n in range(a, b+1):
  if n == 1:
    continue
  for i in range(2, n):
    if n % i == 0:
      break

  else:
    sum += n
print(f"Sum of all Prime numbers between A and B is {sum}")

Enter the value of A. 1
Enter the value of B.100
Sum of all Prime numbers between A and B is 1060


Question 3 Count how many numbers between 1 and N is divisible by 3 or 5.

In [ ]:
num = int(input("Enter the value of N"))
count = 0
divisible_num = 0
for n in range(1, num +1):
  if n % 3 == 0 or n % 5 == 0:
    divisible_num = n
    count+=1
    print(divisible_num)
print(f"Total numbers divisible by 3 or 5 is {count}")

Enter the value of N50
3
5
6
9
10
12
15
18
20
21
24
25
27
30
33
35
36
39
40
42
45
48
50
Total numbers divisible by 3 or 5 is 23


Question 4. Generate a multiplication table from 1 to 10.


In [ ]:
for i in range(1, 11):
  for j in range(1, 11):
    print(f"{i} * {j} = {i*j}")
  print()

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
1 * 10 = 10

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30

4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50

6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60

7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70

8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 10 = 80

9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90

10 * 1 = 10
10 

Question 5. Check if a string is a palindrome using loop.


In [ ]:
string = input("Enter the String. ")
left = 0
right = len(string) - 1
palindrome = True
while left < right:
  if string[left] != string[right]:
    palindrome = False
    break
  left += 1
  right -= 1
if palindrome:
  print(f"{string} is a palindrome.")
else:
  print(f"{string} is not a palindrome")

Enter the String. radar
radar is a palindrome.


Question 6. Find the sum of digits until the result becomes a single digit

In [ ]:
num = int(input("Enter a number. "))
for i in range(100):
  if num < 10:
    break
  digit_sum = 0
  for digit in str(num):
    digit_sum += int(digit)
  num = digit_sum
  print(digit_sum)
print(f"Single digit result is :{num}")

Enter a number. 987
24
6
Single digit result is :6


Question 7. Check if a number is Armstrong number.


In [ ]:
num = int(input("Enter a number. "))
num_len = len(str(num))
armstrong_sum = 0
for d in str(num):
  armstrong_sum += int(d) ** num_len

if armstrong_sum == num:
  print(f"The Given Number {num} is a Armstrong Number")
else:
  print(f"The Given Number {num} is not a Armstrong Number")

Enter a number. 157
The Given Number 157 is not a Armstrong Number


Question 8. Generate the first N prime numbers

In [ ]:
number = int(input("Enter the value of N"))
count = 0
num = 2
while count < number:
  prime = True

  for i in range(2, int(num ** 0.5) + 1):
    if num % i == 0:
      prime = False
      break
  if prime:
    print(num, end = " ")
    count += 1

  num += 1

Enter the value of N5
2 3 5 7 11 

Question 9. Generate the first N Fibonacci numbers using loop.


In [ ]:
number = int(input("Enter the value of N."))
a = 0
b = 1
for i in range(number):
    print(a, end=" ")
    a, b = b, a + b

Enter the value of N.10
0 1 1 2 3 5 8 13 21 34 

Question 10. Count how many even number are there in between 1 and N.


In [ ]:
number = int(input("Enter the value of N ."))
count = 0
for i in range(1, number + 1):
  if i % 2 == 0:
    count += 1
print(f"There are {count} even number in between 1 and {number}")

Enter the value of N .5
There are 2 even number in between 1 and 5


Question 11. Count how many odd numbers are there in between 1 and N.

In [ ]:
number = int(input("Enter the value of N. "))
count = 0
for i in range(1, number + 1):
  if i % 2 != 0:
    count += 1
    print(i, end = " ")
print(f"\nThere are {count} odd numbers in between 1 and {number}")


Enter the value of N. 41
1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 
There are 21 odd numbers in between 1 and 41


Question 12. Reverse a number


In [ ]:
number = int(input("Enter a number."))
reverse_num = 0
while number > 0:
  digit = number % 10
  reverse_num = reverse_num * 10 + digit
  number //= 10
print(f"Reversed number is {reverse_num}")

Enter a number.154
Reversed number is 451


Question 13. For numbers 1 to N:
For numbers 1 to N:

*   If divisible by 3 print "Fizz"
*   If divisible by 5 print "Buzz"
*   If divisible by both 3 and 5 print "FizzBuzz"
*   Else print number





In [ ]:
number = int(input("Enter the value of N. "))
for i in range(1, num + 1):
  if i % 3 == 0 and i % 5 == 0:
    print("FizzBuzz")

  elif i % 3 == 0:
    print("Fizz")

  elif i % 5 == 0:
    print("Buzz")
  else:
    print(i)

Enter the value of N. 15
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz


### String Practice Question

Question 1. Reverse a string without using slicing



In [ ]:
string = input("Enter any string ")
rev = ""
for ch in string:
  rev = ch + rev
print(rev)
print(len(rev))

Enter any string Nausad
dasuaN
6


Question 2. Check if a string is palindrome.


In [ ]:
string = input("Enter a string")
if string == string[::-1]:
  print("The string is a palindrome")
else:
  print("The string is not a palindrome")

Enter a stringradar
The string is a palindrome


In [ ]:
try:
    del sum
    print("sum variable deleted successfully")
except NameError:
    print("sum was not defined")


sum variable deleted successfully


Question 3. Count vowels and consonants in a string.

In [ ]:


string = input("Enter a string").strip().lower()
vowel = 'aeiou'
vowel_count = sum(1 for char in string if char in vowel)
cons_count = sum(1 for char in string if char not in vowel)
print(f"Vowels:{vowel_count}, Consonants: {cons_count}")

Enter a stringNausad
Vowels:3, Consonants: 3


Question 4. Count number of words in sentence

In [ ]:
string = input("Enter the sentence..")
count = len(string.split())
print(count)

Enter the sentence..Ali Nausad
2


Question 5. Convert string to uppercase without using built-in upper().


In [ ]:
string = input("Enter a string: ")
result = ""

for char in string:
    if 'a' <= char <= 'z':
        result += chr(ord(char) - 32)
    else:
        result += char

print("Uppercase string:", result)

Enter a string: Hi How are you
Uppercase string: HI HOW ARE YOU


Question 6. Find length of string without using len().

In [ ]:
string = input("Enter a string")
count = 0
for ch in string:
  count += 1
print(f"Total count: {count}")

Enter a stringHi Who are you
Total count: 14


Question 7. Check if two strings are anagrams.

In [ ]:
string1 = input("Enter the first string")
string2 = input("Enter the second string")
if sorted(string1) == sorted(string2):
  print("The strings are anagrams")
else:
  print("The strings are not anagrams")


Enter the first stringjkls
Enter the second stringajsfh
The strings are not anagrams


Question 8. Remove Spaces from a string

In [ ]:
string = input("Enter a string")
string = string.replace(" ", "")
string

Enter a stringhsdf


'hsdf'

Question 9. Count occurrences of a character in a string.


In [ ]:
string = input("Enter a string")
count = 0
str_occr = input("Enter the character whose occurrences you want to count...")
for ch in string:
  if ch == str_occr:
    count+=1
print(count)

Enter a stringjkdsfh
Enter the character whose occurrences you want to count...skdljfh
0


Question 10.Remove digits from a string.


In [ ]:
string = input("Enter a string")
result = ""
for ch in string:
  if not ch.isdigit():
    result += ch
result

Enter a stringsdkfl


'sdkfl'

Question 11.Remove alphabets from a string.


In [ ]:
string2 = input("Enter a string")
result2 = ""
for al in string2:
  if not al.isalpha():
    result2 += al
result2

Enter a stringkljdfh


''

Question 12.Check if a string contains only digits


In [ ]:
string = input("Enter the string")
count = 0
for ch in string:
  if ch.isdigit():
    count += 1
if count == len(string):
  print("Yes")

else:
  print("No")

Enter the stringsdkfjh
No


Question 13. Replace all spaces with underscores _.

In [ ]:
string = input("Enter a string")
result = ""
result = string.replace(" ","").replace("_","")
result


# string = input("Enter a string")
# result = "".join(char for char in string if char not in [" ", "_"])
# result

Enter a stringHi My name is Nausad_ali


'HiMynameisNausadali'

Question 14.Find first non-repeating character in a string.


In [ ]:
string = input("Enter a string")
for char in string:
  if string.count(char) == 1:
    print("First non-repeating character found", char)
    break
else:
  print("No non-repeating character foundd")


Enter a stringNausad
First non-repeating character found N


Question 15. Check if a string is a pangram (contains all alphabets).

In [ ]:
string = input("Enter a string").lower()

for ch in "abcdefghijklmnopqrstuvwxyz":
    if ch not in string:
        print("The string is not a pangram")
        break
else:
    print("The string is a pangram")

Enter a string: hello guys dekho na dekho na guys
The string is not a pangram


# NumPy

Create a Numpy array with values from 1 to 10.

In [ ]:
import numpy as np


In [ ]:
arr1 = np.array(range(1,11))

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

create a NumPy array of five zeros.


In [ ]:
arrZeros = np.zeros(5)

In [ ]:
arrZeros

array([0., 0., 0., 0., 0.])

Create a NumPy array of five ones.

In [ ]:
arrOnes = np.ones(5)

In [ ]:
arrOnes

array([1., 1., 1., 1., 1.])

Create a NumPy array using arange() from 5 to 50 with step of 5.

In [ ]:
arrArange = np.arange(5,50 +1 ,5)

In [ ]:
arrArange

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

Create a 2D NumPy array of shape(3,3)

In [ ]:
arr3_3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
arr3_3, arr3_3.shape

(array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]),
 (1, 3, 3))

Find the dimension of a given NumPy array.

In [ ]:
arr3_3.ndim

3

Find the shape of a NumPy array.

In [ ]:
arr3_3.shape

(1, 3, 3)

Access the first and last element of a NumPy array.


In [ ]:
print(f"The first element of a numpy array {arr1[0]}\n")
print(f"The last element of a numpy array {arr1[-1]}\n")

The first element of a numpy array 1

The last element of a numpy array 10



Extract the second row from a 2D NumPy array.

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr[:, 1], arr.ndim

(array([2, 5]), 2)

Extract the third column from a 2D NumPy array.

In [ ]:
arr2D = np.array([[74, 78, 54],[45,74,1]])
arr2D[:,2]

array([54,  1])

Add 10 to every element of an array by 5.

In [ ]:
arr_add_5 = np.array([1,2,3,4,5,6])
arr_add_5 + 5

array([ 6,  7,  8,  9, 10, 11])

Add 10 to every element of a NumPy array.

In [ ]:
arr_add_10 = np.array([[[10,12,14,74],[20,4,16,74],[10,45,87,74]]])

In [ ]:
arr_add_10 + 10

array([[[20, 22, 24, 84],
        [30, 14, 26, 84],
        [20, 55, 97, 84]]])

Multiply all element of an array by 5.

In [ ]:
arr_Multiply_5 = np.array([10,14,5,6])
arr_Multiply_5 * 5

array([50, 70, 25, 30])

Find the sum of all elements in an array.

In [ ]:
arr = np.array([1,21,10])
arr.sum()

np.int64(32)

Find the maximum and minimum value of an array

In [ ]:
arr.max()

np.int64(21)

In [ ]:
arr.min()

np.int64(1)

Count the total number of elements in an array.

In [ ]:
arr3_3.size

6

In [ ]:
arr3_3

array([[[1, 2, 3],
        [4, 5, 6]]])

Reshape a 1D array of 12 elements into a 3x4 array

In [ ]:
arr1D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1D.size

12

In [ ]:
arrResize = arr1D.reshape(3,4)

In [ ]:
arrResize.shape, arrResize

((4, 3),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]))

Convert an integer array into float array.

In [ ]:
arr = np.array([1,2,3,4,5])
arrFloat = arr.astype(float)
arrFloat

array([1., 2., 3., 4., 5.])

In [ ]:
import numpy as np
z = np.zeros(10)


In [ ]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z.shape

(10,)

In [ ]:
z.shape = (10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
z = np.zeros(4)
z.shape = (2,2)
z

array([[0., 0.],
       [0., 0.]])

Creating an Array

In [ ]:
z = np.empty(3)
z

array([0. , 0.5, 1. ])

In [ ]:
z = np.linspace(2,4,5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
z = np.identity(2)

In [ ]:
z

array([[1., 0.],
       [0., 1.]])

In [ ]:
z = np.array([10,20])
z

array([10, 20])

In [ ]:
z = np.array([[1,2],[1,2]])
z

array([[1, 2],
       [1, 2]])

In [ ]:
z = np.array([10,20], dtype=float)
z

array([10., 20.])

In [ ]:
na = np.linspace(10,20,2)
na is np.asarray(na)

True

In [ ]:
na is np.array(na)

False

Array indexing

In [ ]:
z = np.linspace(1,2,5)
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
z[0]

np.float64(1.0)

In [ ]:
z[0:2]

array([1.  , 1.25])

In [ ]:
z[-1]

np.float64(2.0)

In [ ]:
z = np.array([[1,2],[3,4]])

In [ ]:
z

array([[1, 2],
       [3, 4]])

In [ ]:
z[0, 1]

np.int64(2)

In [ ]:
z[0, :]

array([1, 2])

In [ ]:
z[:, 1]

array([2, 4])

In [ ]:
z = np.linspace(2,4,5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
indices = np.array((0,2,3))

In [ ]:
z[indices]

array([2. , 3. , 3.5])

In [ ]:
d = np.array([0,1,1,0,0],dtype=bool)
d

array([False,  True,  True, False, False])

In [ ]:
z[d]

array([2.5, 3. ])

In [ ]:
z[:] = 42

In [ ]:
z

array([42., 42., 42., 42., 42.])

In [ ]:
a = np.array((4,3,2,1))
a

array([4, 3, 2, 1])

In [ ]:
a.sort()
a

array([1, 2, 3, 4])

In [ ]:
a.sum()

np.int64(10)

In [ ]:
a.mean()

np.float64(2.5)

In [ ]:
a.max()

np.int64(4)

In [ ]:
a.argmax()

np.int64(3)

In [ ]:
a.cumsum()

array([ 1,  3,  6, 10])

In [ ]:
a.cumprod()

array([ 1,  2,  6, 24])

In [ ]:
a.var()

np.float64(1.25)

In [ ]:
a.std()

np.float64(1.118033988749895)

In [ ]:
a.shape = (2,2)
a.T

array([[1, 3],
       [2, 4]])

In [ ]:
z = np.linspace(2, 4, 5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
z.searchsorted(2.2)

np.int64(1)

In [ ]:
a = np.array((4,3,2,1))
a

array([4, 3, 2, 1])

In [ ]:
np.sum(a)

np.int64(10)

# Assignment


 Q1. WAP to print "Hello World".**bold text**

In [ ]:
"Hello World"

'Hello World'

Q2. WAP to do arithmetical operations addition and division

In [ ]:
a = float(input("Enter the first digit....."))
operation = input("Enter the operation you want to do (Either addition or division  ( + , / )).......")
b = float(input("Enter the second digit......."))
if operation == '+':
  print(a+b)

elif operation == '/':
  print(a/b)
else:
  print("wrong operation")


Enter the first digit.....40
Enter the operation you want to do (Either addition or division  ( + , / )).......+
Enter the second digit.......60
100.0


Q3. WAP to find the area of a triangle.

In [ ]:
base = float(input("Enter the value of base......"))
height = float(input("Enter the value of height........"))
area = 0.5*base*height
print(f"The area of the triangle is {area} square units.")

Enter the value of base......12.5
Enter the value of height........24.7
The area of the triangle is 154.375.


Q4. WAP to swap two variables

In [ ]:
var1 = 5
var2 = 80
temp_var = 0
temp_var = var1
var1 = var2
var2 = temp_var
print(var1, var2)

# without extra variable
a = 10
b = 20
a, b = b, a
print(f"a = {a}      ,        b = {b}")

80 5
a = 20      ,        b = 10


Q5. WAP to generate a random number.

In [ ]:
import random
randomNumber = random.randint(1, 10000000000)
print(f"The random generated Number is {randomNumber}." )

The random generated Number is 7910557197.


Q6. WAP to convert kilometers to miles.

In [ ]:
distance = float(input("Enter the distance in kilometers......"))
miles = distance * 0.621
print(f"After converting the distance from kilometers to miles the result is {miles}.")

Enter the distance in kilometers......24.54
After converting the distance from kilometers to miles the result is 15.239339999999999.


Q7. WAP to convert Celsius to Fahrenheit.

In [ ]:
cel = float(input("Enter the temperature in celsius here......."))
fahren = (9/5*cel) + 32
print(f"The temperature in fahrenheit is {fahren}` F..")

Enter the temperature in celsius here.......25
The temperature in fahrenheit is 77.0` F..


Q8. WAP to display calendar.

In [ ]:
import calendar
year = int(input("Enter the year"))
month = input("Enter the name of the months which you want to display.....").strip().capitalize()
monthNumber = list(calendar.month_name).index(month)
print(calendar.month(year, monthNumber))

Enter the year2026
Enter the name of the months which you want to display.....January
    January 2026
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30 31



Q9. WAP to swap two variable without temp variable.

In [ ]:
a = 1000
b = 2000
a, b = b, a
print(f"After swapping the variable the value of a is {a}   and the value of b is {b}.")

After swapping the variable the value of a is 2000   and the value of b is 1000.


Q10. WAP to Check if a number is positive, negative or Zero.

In [ ]:
number = float(input("Enter  any number ....."))
if number == 0:
  print("The number is zero")
elif number > 0:
  print("The number is posiitive")
else:
  print("The number is negative")

Enter  any number .....50
The number is posiitive


Q11. WAP to check if a number is odd or even.


In [ ]:
number = int(input("Enter a integer number here......."))
if number%2 == 0:
  print(f"The given number {number} is even.")
else:
  print(f"The given number {number} is odd.")

Enter a integer number here.......100
The given number 100 is even.


Q12. WAP to check Leap year.

In [ ]:
year = int(input("Enter the year ......"))
if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
  print(f"The year {year} is a leap year.")
else:
  print(f"The year {year} is not a leap year.")

Enter the year ......2024
The year 2024 is a leap year.


Q13. WAP to Check Prime Number.

In [ ]:
number = int(input("Enter any number here......"))
for i in range(2,number):
  if number % i == 0:
    print(f"The number {number} is not a prime number.")
    break
else:
  print(f"The Number {number} is a prime number.")

Enter any number here......13
The Number 13 is a prime number.


Q14. WAP to print all the prime numbers in an interval of 1 - 10

In [ ]:
number = int(input("Enter any number here......"))
for n in range(2, number+1):
  for i in range(2,n):
    if n % i == 0:
      break
  else:
    print(f"{n} is a prime number.")

Enter any number here......10
2 is a prime number.
3 is a prime number.
5 is a prime number.
7 is a prime number.


Q15. WAP to find the factorial of a number.

In [ ]:
def factorial (a):
  if a == 0 or a == 1: return 1
  return a * factorial(a-1)

factorial(5)

120

Q17. WAP to find Armstrong number in an interval.





In [ ]:
lower = int(input("Enter the lower limit......"))
upper = int(input("Enter the upper limit....."))
print(f"All the Armstrong numbers between the given interval are listed below:- ")
for num in range(lower, upper + 1):
    order = len(str(num))
    temp = num
    sum = 0

    while temp > 0:
        digit = temp % 10
        sum += digit ** order
        temp //= 10

    if sum == num:

      print(sum)

Enter the lower limit......1
Enter the upper limit.....158
All the Armstrong numbers between the given interval are listed below:- 
1
2
3
4
5
6
7
8
9
153


Q18. WAP to find the sum of natural numbers.


In [ ]:
start = int(input("Enter the starting number here......."))
end = int(input("Enter the ending number here......."))
sum1 = 0
if start < 0 or end < start:
  print("Enter natural numbers only")
else:
  for i in range(start, end + 1):
    sum1 += i
  print(f"The sum of natural numbers from {start} to {end} is {sum1}")

Enter the starting number here.......1
Enter the ending number here.......10
The sum of natural numbers from 1 to 10 is 55


Q19. WAP to convert decimal to binary, octal and hexadecimal.

In [ ]:
number = float(input("Enter the number here......."))
number = int(number)
print(f"The binary of the given decimal number {number} is" + bin(number))
print(f"The Octal of the given decimal number {number} is " + oct(number))
print(f"The Hexadecimal of the given decimal number {number} is " + hex(number))

Enter the number here.......15.5
The binary of the given decimal number 15 is0b1111
The Octal of the given decimal number 15 is 0o17
The Hexadecimal of the given decimal number 15 is 0xf


Q20. How can we manually convert a decimal number to binary, octal and hexadecimal?

Q21. Converting a decimal number to binary, octal and hexadecimal involves dividing the decimal number by the base repeatedly and noting the remainders at each step.

In [ ]:
number = float(input("Enter a decimal number here......."))
temp = int(number)

# Decimal to binary
binary = ""
t = temp
while t > 0:
  binary = str(t%2)+binary
  t //= 2
print(f"The binary of the given decimal number {number} is " + binary)

# Decimal to octal
octal = ""
t = temp
while t > 0:
  octal = str(t % 8) + octal
  t //= 8
print(f"The octal of the given decimal number {number} is " + octal)

# Decimal to hexadecimal
hex_digits = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
hexadecimal = ""
t = temp
while t > 0:
  hexadecimal = hex_digits[t % 16] + hexadecimal
  t //= 16
print(f"The hexadecimal of the given decimal number {number} is " + hexadecimal)


Enter a decimal number here.......27
The binary of the given decimal number 27.0 is 11011
The octal of the given decimal number 27.0 is 33
The hexadecimal of the given decimal number 27.0 is 1B


Q21. Converting a decimal number to binary, octal and hexadecimal involves dividing the decimal number by the base repeatedly and noting the remainders at each step.

Q23. WAP to make a simple calculator with 4 basic mathematical operations.

In [ ]:
a = float(input("Enter the first digit here....."))
ope = input("Enter the operator ( + , - , / , * ) here .........")
b = float(input("Enter the second digit here......."))
if ope == "+":
  print(a + b)
elif ope == "-":
  print(a - b)
elif ope == "*":
  print(a * b)
elif ope == "/":
  print(a / b)
else:
  print("Please provide correct operator")


Enter the first digit here.....1
Enter the operator ( + , - , / , * ) here .........+
Enter the second digit here.......2
3.0


Q24. WAP to display fibonacci sequence using recursion.




In [ ]:
def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)
num = int(input("How many Fibonacci Sequence you want...."))
print("Fibonacci Series:")
for i in range(num):
    print(fibonacci(i), end=" ")

How many Fibonacci Sequence you want....10
Fibonacci Series:
0 1 1 2 3 5 8 13 21 34 

Q25. WAP to find largest element in an array.

In [ ]:
import numpy as np
arr = np.array([1,4,54,74,98,21])
arr.max()

np.int64(98)

Q26. WAP for array rotation.

In [ ]:
arr_rotation =arr.reshape(3,2)
arr_rotation

array([[ 1,  4],
       [54, 74],
       [98, 21]])

Q27. WAP to split the array and add the first part to the end.




In [ ]:
arr_split = np.array([1,2,3,4,5,6,7,7,8,89])
n = int(input("Enter from where you want to split the array......"))
result = np.roll(arr_split, -n)
result
len(arr_split)

Enter from where you want to split the array......5


10

Q28. WAP to check if given array is Monotonic.

In [ ]:
def monotonic(arr):
    increasing = True
    Decreasing = True

    for i in range(1, len(arr)):
        if arr[i] < arr[i - 1]:
            increasing = False
        if arr[i] > arr[i - 1]:
            Decreasing = False

    return increasing or Decreasing


arr = np.array(list(map(int, input("Enter array elements: ").split(","))))

if monotonic(arr):
    print("Array is Monotonic")
else:
    print("Array is NOT Monotonic")

Enter array elements: 24,21,20,19
Array is Monotonic


Q30. WAP to Add Two Matrices.


In [ ]:
matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[1,2,3],[4,5,6]])
add = matrix1 + matrix2
add

array([[ 2,  4,  6],
       [ 8, 10, 12]])

Q31. WAP to Multiply Two Matrices.

In [ ]:
matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[1,2,3],[4,5,6]])
multi = matrix1 * matrix2
multi

array([[ 1,  4,  9],
       [16, 25, 36]])

Q32. WAP to Transpose a Matrix

In [ ]:
matrix = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
transposed_matrix = matrix.T
print(f"Original Matrix is \n{matrix}\nand Transposed Matrix is \n{transposed_matrix}")


Original Matrix is 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
and Transposed Matrix is 
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Q33. WAP to sord words in alphabetix order.

In [ ]:
sentence = input("Enter a sentence.....").lower().split()
sentence.sort()
print(sentence)


Enter a sentence.....This is me Nausad Ali
['ali', 'is', 'me', 'nausad', 'this']


Q34. WAP to remove punctuation from a string.

In [ ]:
import string
strn = input("Enter a string here......")
result = ""
for ch in strn:
  if ch not in string.punctuation:
    result+=ch
print(f"String without punctuation {result}   .")

Enter a string here......Hi! This_is_me@Nausad#Ali$.
String without punctuation Hi ThisismeNausadAli   .


Q35. WAP to print all disarium numbers between 1 to 100.


In [ ]:
num = int(input("Enter a number here......"))
digits = str(num)
total = 0
for i in range(len(digits)):
  total += int(digits[i]) ** (i + 1)

if total == num:
  print("This is Disarium Number.")
else:
  print("This is not a Disarium Number.")

Enter a number here......1
This is Disarium Number.


In [ ]:
for num in range(1, 101):
    digits = str(num)
    total = 0

    for i in range(len(digits)):
        total += int(digits[i]) ** (i + 1)

    if total == num:
        print(num)



1
2
3
4
5
6
7
8
9
89


Q36. WAP to print all happy numbers between 1 and 100.

In [ ]:
for num in range(1, 100+1):
  temp = num
  s = set()

  while temp!=1 and temp not in s:
    s.add(temp)
    total = 0
    while temp > 0:
      digit = temp % 10
      total += digit * digit
      temp //= 10
    temp = total
  if temp == 1:
    print(num)

1
7
10
13
19
23
28
31
32
44
49
68
70
79
82
86
91
94
97
100


Q37. WAP to multiply all numbers in the list.

In [ ]:
list1 = [1,2,4,5,7,8]
multiply = 1

for i in list1:
  multiply *= i
print(multiply)

2240


Q38. WAP to find the smallest number in a list.

In [ ]:
list2 = [12, 10,13, 15,85, 45, 9, 102, 144]
print(f"The smallest number from the list {list2} is.")
list2.sort()
list2[0]

The smallest number from the list [12, 10, 13, 15, 85, 45, 9, 102, 144] is.


9

Q39. WAP to find largest number in a list.






In [ ]:
list3 = [1,2,4,57,14,4,654,1,45,98745,244151,46,5465]
print(f"The Largest number from the list {list3} is. ")
list3.sort()
list3[-1]

The Largest number from the list [1, 2, 4, 57, 14, 4, 654, 1, 45, 98745, 244151, 46, 5465] is. 


244151

Q40. WAP to find second largest number in a list.


In [ ]:
list3 = [1,2,4,57,14,4,654,1,45,98745,244151,46,5465]
print(f"The Largest number from the list {list3} is. ")
list3.sort()
list3[-2]

The Largest number from the list [1, 2, 4, 57, 14, 4, 654, 1, 45, 98745, 244151, 46, 5465] is. 


98745

Q41. WAP to find the N largest elements in a list.

In [ ]:
N = int(input("Enter the value of N"))
list3 = [1,2,4,57,14,4,654,1,45,98745,244151,46,5465]
print(f"The Largest number from the list {list3} is. ")
largest = sorted(list3, reverse=True) [:N]
print(largest)



Enter the value of N5
The Largest number from the list [1, 2, 4, 57, 14, 4, 654, 1, 45, 98745, 244151, 46, 5465] is. 
[244151, 98745, 5465, 654, 57]


Q42. WAP to print even numbers in a list.

In [ ]:
lis = [1,2,4,5,7,8,9,6,3,4,1,52]
eve_lis = []
for i in lis:
  if i % 2 == 0:
    eve_lis.append(i)
print(eve_lis)

[2, 4, 8, 6, 4, 52]


Q43. WAP to print odd numbers in a list.

In [ ]:
lis = [1,2,4,5,7,8,9,6,3,4,1,52]
eve_lis = []
for i in lis:
  if i % 2 == 0:
    continue
  else:
    eve_lis.append(i)
print(eve_lis)

[1, 5, 7, 9, 3, 1]


Q44. WAP to Remove empty list from list.

In [ ]:
lis = [[1,2],[],[4,5],[],[5],[]]
result = []
for i in lis:
  if i != []:
    result.append(i)
print(f"After removing the empty list {lis}\nresult is {result}")

After removing the empty list [[1, 2], [], [4, 5], [], [5], []]
result is [[1, 2], [4, 5], [5]]


Q45. WAP to Cloning or Copying a list.

In [ ]:
list4 = list(map(int,input("Enter the elements here...").split(",")))
ls_copy = list4.copy()
ls_copy


Enter the elements here...1,5,4,5,7,6,4,5,5


[1, 5, 4, 5, 7, 6, 4, 5, 5]

Q46. WAP to count the occurences of an element in a list.

In [ ]:
list5 = list(map(int,input("Enter the elements here...").split(",")))
ele = int(input("Enter the element whose occurences you want to count......"))
count = 0
for i in list5:
  if i == ele:
    count+=1
print(count)

Enter the elements here...1,1,4,1,5,2,5,4,6,2,1,55,1,5,1
Enter the element whose occurences you want to count......1
6


Q47. WAP to find words which are greater than given length k.

In [ ]:
sentence = input("Enter a sentence here.......").lower().split()
k = int(input("Enter the length limit here......."))
for i in range(len(sentence)):
  if len(sentence[i]) > k:
    print(sentence[i])
  else:
    continue

Enter a sentence here.......This is me Nausad Ali
Enter the length limit here.......4
nausad


Q48. WAP to for removing Ith character from a string.

In [ ]:
st = input("Enter a string here.........")
Ith = int(input("Enter the value of I which you want to remove........"))
result = ""
count = 0
for i in st:
  count += 1
  if Ith == count:
    continue
  else:
    result = i + result
print(result[::-1])


Enter a string here.........Nausad
Enter the value of I which you want to remove........4
Nauad


Q49. WAP to split and join a string.

In [ ]:
#Split
stri = input("Enter string here.....").split(" ")
print(f"The splitted string is {stri}")
# Join
stri2 = input("Enter any string here.....")
join_result = " ".join(stri) + " " + stri2

print(join_result)

Enter string here.....Hi this is me Nausad Ali
The splitted string is ['Hi', 'this', 'is', 'me', 'Nausad', 'Ali']
Enter any string here.....hello
Hi this is me Nausad Ali hello


Q50. WAP to check if a given string is binary string or not.

In [ ]:
s = input("Enter a string...")
binary = True
for i in s:
  if i != '0' and i != '1':
    print("String is not binary")
    break
else:
  print("String is binary")

Enter a string...101010s
String is not binary


Q51. WAP to find uncommon words from two strings.

In [ ]:
str1 = input("Ennter a sentence.......").lower().split()
str2 = input("Enter second sentence.......").lower().split()
uncommon_words = []
for word in str1:
  if word not in str2:
    uncommon_words.append(word)
for word in str2:
  if word not in str1:
    uncommon_words.append(word)

print("Uncommon words are...uncommon_words", uncommon_words)

Ennter a sentence.......Hi this is me Nausad Ali
Enter second sentence.......Hi My name is Nausad Ali
Uncommon words are...uncommon_words ['this', 'me', 'my', 'name']


Q52. WAP to find all duplicate characters in string.

In [ ]:
s = input("Enter a string here........")
duplicates = []
for i in s:
  if s.count(i) > 1 and i not in duplicates:
    duplicates.append(i)

print("Duplicate characters are. " , duplicates)

Enter a string here........Nausad ali this that
Duplicate characters are.  ['a', 's', ' ', 'i', 't', 'h']


Q53. WAP to check if a tring contains any special character.


In [ ]:
s = input("Enter a string here.........")
special = False
for i in s:
  if not i.isalnum():
    special = True
    break
if special:
  print("String contains special character")
else:
  print("String does not contain special character")

Enter a string here.........Nausad@ali
String contains special character


Q54. WAP to Extract Unique dictionary values.

In [ ]:
dict1 = {
    'Nausad Ali' : 26,
    'Manjeet Gupta' : 8,
    'Pratik Tiwari' : 4,
    'Mariyam': 26,
    'Prasiddh': 18,
    'Deepak Kumar' : 26
}
unique_values = []
for value in dict1.values():
  if value not in unique_values:
    unique_values.append(value)

print("Unique dictionary values are.", unique_values)

Unique dictionary values are. [26, 8, 4, 18]


Q55. Write a Python program to find the sum of all items in a dictionary.


In [ ]:
dict1 = {
    'Nausad Ali' : 26,
    'Manjeet Gupta' : 8,
    'Pratik Tiwari' : 4,
    'Mariyam': 26,
    'Prasiddh': 18,
    'Deepak Kumar' : 26
}
summ = 0
for i in dict1.values():
  summ += i

print(summ)

108


Q56. Write a Python program to Merging two Dictionaries.


In [ ]:
dict1 = {
    'Nausad Ali' : 26,
    'Manjeet Gupta' : 8,
    'Pratik Tiwari' : 4,
    'Mariyam': 26,
    'Prasiddh': 18,
    'Deepak Kumar' : 26
}
dict2 = {
    'Nausad Ali' : 40,
    'Manjeet Gupta' : 25,
    'Pratik Tiwari' : 21,
    'Mariyam' : 20,
    'Prasiddh' : 28,
    'Deepak Kumar' : 36
}
merged = {}

for key in dict1:
    merged[key] = dict1[key]

for key in dict2:
    if key in merged:
        merged[key] = [merged[key], dict2[key]]
    else:
        merged[key] = dict2[key]
print(merged)

{'Nausad Ali': [26, 40], 'Manjeet Gupta': [8, 25], 'Pratik Tiwari': [4, 21], 'Mariyam': [26, 20], 'Prasiddh': [18, 28], 'Deepak Kumar': [26, 36]}


Q62. WAP that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.
 Suppose the following input is supplied to the program:-

 without,hello,bag,world

 then the output should be:-

 bag,hello,without,world

In [ ]:
s = input("Enter comma-seperated words:........")
word_split = s.split(",")
word_split.sort()
result = ""
result = ",".join(word_split)
print(result)

Enter comma-seperated words:........without,hello,bag,world
bag,hello,without,world


Q63. WAP that accepts a sequence of whitespace separated words as input and print the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:-

hello world and practice makes perfect and hello world again

then the output should be:-

again and hello makes perfect practice world

In [ ]:
s = input("Enter whitespace separated words:--........")
word_split = s.split(" ")
word_split.sort()
result = []
for word in word_split:
  if word not in result:
    result.append(word)
  else:
    continue
  result2 = ""
  result2 = " ".join(result)

print(result2)

Enter whitespace separated words:--........hello world and practice makes perfect and hello world again
again and hello makes perfect practice world


Q64. Define a class with a generator which can iterate the numbers, which are divisible by 7, between a given range 0 and n.

In [ ]:
class divBySeven:
  def __init__(self, n):
    self.n = n

  def generate(self):
    for i in range(0, self.n+1):
      if i == 0:
        continue
      elif i % 7 == 0:
        yield i
n = int(input("Enter the value of n......"))
obj = divBySeven(n)
for num in obj.generate():
  print(num)

Enter the value of n......100
7
14
21
28
35
42
49
56
63
70
77
84
91
98


# Iris Dataset Modelling Using NumPy

In [ ]:
import numpy as np
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()
X = iris.data
y = iris.target

print("X shape: ", X.shape)
print("y shape: ", y.shape)
print('Features name: ', iris.feature_names)
print('Class name: ', iris.target_names)

X shape:  (150, 4)
y shape:  (150,)
Features name:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Class name:  ['setosa' 'versicolor' 'virginica']


In [ ]:
# inspect the data
print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
# Basic Statistics
mean = np.mean(X, axis = 0)
std = np.std(X, axis=0)

for i, name in enumerate(iris.feature_names):
  print(name, "mean:", round(mean[i], 2), "Std: ",round(std[i], 2))



sepal length (cm) mean: 5.84 Std:  0.83
sepal width (cm) mean: 3.06 Std:  0.43
petal length (cm) mean: 3.76 Std:  1.76
petal width (cm) mean: 1.2 Std:  0.76


In [ ]:
# Normaize the features (Z-score)
X_norm = (X-mean) / std

print(X_norm[:5])

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]


In [ ]:
# Train-Test Split (Manual)
# 80% training data
# 20% testing data

np.random.seed(42)
indices = np.random.permutation(len(X_norm))
split = int(0.8 * len(X_norm))

train_idx = indices[:split]
test_idx = indices[split:]

X_train, X_test = X_norm[train_idx], X_norm[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

print("Train samples: ", X_train.shape[0])
print("Test samples: ", X_test.shape[0])

Train samples:  120
Test samples:  30


In [ ]:
# Nearest Centroid Classifier

centroids = np.array([
    X_train[y_train==0].mean(axis=0),
    X_train[y_train == 1].mean(axis=0),
    X_train[y_train == 2].mean(axis=0)
])
print(centroids)

[[-1.03875619  0.86910878 -1.30189431 -1.25115881]
 [ 0.09351674 -0.6573003   0.28765567  0.1831375 ]
 [ 0.92640277 -0.18649977  1.01852669  1.11628711]]


In [ ]:
# Prediction Function
def Predict (X, centroids):
  distances = np.linalg.norm(
      X[:, None, :] - centroids[None, :, :],
      axis=2
  )
  return np.argmin(distances, axis=1)

In [ ]:
y_pred = Predict(X_test, centroids)
accuracy = np.mean(y_pred == y_test)
print("Model Accuracy: ", accuracy)

Model Accuracy:  0.8666666666666667


# Breast Cancer Prediction Model using NumPy

In [ ]:
import numpy as np
from sklearn.datasets import load_breast_cancer

In [ ]:
breast_cancer = load_breast_cancer()

In [ ]:
breast_cancer.target_names, breast_cancer.feature_names

(array(['malignant', 'benign'], dtype='<U9'),
 array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'))

In [ ]:
X = breast_cancer.data

In [ ]:
y = breast_cancer.target

In [ ]:
X.shape

(569, 30)

In [ ]:
y.shape

(569,)

In [ ]:
print(X[:5])
print(y[:5])

[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 3.861e+02 1.425e-01 2.839e-01 2.414

In [ ]:
mean = np.mean(X, axis=0)
std  = np.std(X, axis=0)
minimum = np.min(X, axis=0)
maximum= np.max(X, axis=0)
count = X.shape[0]

for i, name in enumerate(breast_cancer.feature_names):
    print(
        f"{name:30s} \n"
        f"mean={mean[i]:.2f} \n"
        f"count={count} \n"
        f"std={std[i]:.2f} "
        f"min={minimum[i]:.2f} \n"
        f"max={maximum[i]:.2f} \n"
    )

mean radius                    
mean=14.13 
count=569 
std=3.52 min=6.98 
max=28.11 

mean texture                   
mean=19.29 
count=569 
std=4.30 min=9.71 
max=39.28 

mean perimeter                 
mean=91.97 
count=569 
std=24.28 min=43.79 
max=188.50 

mean area                      
mean=654.89 
count=569 
std=351.60 min=143.50 
max=2501.00 

mean smoothness                
mean=0.10 
count=569 
std=0.01 min=0.05 
max=0.16 

mean compactness               
mean=0.10 
count=569 
std=0.05 min=0.02 
max=0.35 

mean concavity                 
mean=0.09 
count=569 
std=0.08 min=0.00 
max=0.43 

mean concave points            
mean=0.05 
count=569 
std=0.04 min=0.00 
max=0.20 

mean symmetry                  
mean=0.18 
count=569 
std=0.03 min=0.11 
max=0.30 

mean fractal dimension         
mean=0.06 
count=569 
std=0.01 min=0.05 
max=0.10 

radius error                   
mean=0.41 
count=569 
std=0.28 min=0.11 
max=2.87 

texture error                  
mean=1.22 
count=569 
std=

In [ ]:
X_norm = (X-mean) / std
print(X_norm[:5])

[[ 1.09706398e+00 -2.07333501e+00  1.26993369e+00  9.84374905e-01
   1.56846633e+00  3.28351467e+00  2.65287398e+00  2.53247522e+00
   2.21751501e+00  2.25574689e+00  2.48973393e+00 -5.65265059e-01
   2.83303087e+00  2.48757756e+00 -2.14001647e-01  1.31686157e+00
   7.24026158e-01  6.60819941e-01  1.14875667e+00  9.07083081e-01
   1.88668963e+00 -1.35929347e+00  2.30360062e+00  2.00123749e+00
   1.30768627e+00  2.61666502e+00  2.10952635e+00  2.29607613e+00
   2.75062224e+00  1.93701461e+00]
 [ 1.82982061e+00 -3.53632408e-01  1.68595471e+00  1.90870825e+00
  -8.26962447e-01 -4.87071673e-01 -2.38458552e-02  5.48144156e-01
   1.39236330e-03 -8.68652457e-01  4.99254601e-01 -8.76243603e-01
   2.63326966e-01  7.42401948e-01 -6.05350847e-01 -6.92926270e-01
  -4.40780058e-01  2.60162067e-01 -8.05450380e-01 -9.94437403e-02
   1.80592744e+00 -3.69203222e-01  1.53512599e+00  1.89048899e+00
  -3.75611957e-01 -4.30444219e-01 -1.46748968e-01  1.08708430e+00
  -2.43889668e-01  2.81189987e-01]
 [ 1.5

In [ ]:
np.random.seed(42)
indices = np.random.permutation(len(X_norm))
split = int(0.8 * len(X_norm))

train_idx = indices[:split]
test_idx = indices[split:]

X_train, X_test = X_norm[train_idx], X_norm[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

print("Train Sample: ", X_train.shape[0])
print("Test Sample: ", X_test.shape[0])


Train Sample:  455
Test Sample:  114


In [ ]:
breast_cancer.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
centroids = np.array([
    X_train[y_train == 0].mean(axis=0),
    X_train[y_train == 1].mean(axis=0)
])
print(centroids)

[[ 0.95152822  0.55271088  0.97026375  0.91413074  0.48880894  0.80555476
   0.91268575  1.02028502  0.45992873  0.00850938  0.70758914 -0.00538052
   0.69382959  0.66110496 -0.11418346  0.38070399  0.31759139  0.50040146
  -0.0352869   0.10361992  1.02733478  0.60541194  1.04154938  0.96534747
   0.54629403  0.77781296  0.85631958  1.02877104  0.57375626  0.41765396]
 [-0.5743909  -0.30655343 -0.58257994 -0.55484362 -0.28304743 -0.4479153
  -0.51723173 -0.59318486 -0.25467725  0.03512879 -0.43766396  0.04855188
  -0.42359868 -0.42411011  0.05452073 -0.21013373 -0.16232891 -0.31899412
   0.03434553 -0.05640878 -0.60575142 -0.32909311 -0.60805649 -0.57029845
  -0.31868878 -0.43593805 -0.48184049 -0.60724635 -0.30130972 -0.2264705 ]]


In [ ]:
def predict (X, centroids):
  distances = np.linalg.norm(
      X[:,None,:] - centroids[None,:,:],
      axis = 2

  )
  return np.argmin(distances, axis= 1)

In [ ]:
y_pred = predict(X_test, centroids)
accuracy = np.mean(y_pred == y_test)
print("Model Accuracy :- ", accuracy)

Model Accuracy :-  0.9298245614035088


# Data Handling and Analysis with Pandas

## Pandas Basics

### Introduction to Pandas
Pandas = Python Data Analysis Library

core Structures: Series(1D) and DataFrames (2D table)

In [2]:
import pandas as pd

# Create a Series
s = pd.Series([10,1,2,15,5,6], name = "Marks")
print(s)

# Create a DataFrame
data = {
    'Name': ["Amrit", "Bittu", "Charanjit", "Davinder"],
    'Age': [23,25,22,24],
    'Marks': [88,92,95,70]
}
df = pd.DataFrame(data)
print(df)

0    10
1     1
2     2
3    15
4     5
5     6
Name: Marks, dtype: int64
        Name  Age  Marks
0      Amrit   23     88
1      Bittu   25     92
2  Charanjit   22     95
3   Davinder   24     70


### 2. Reading and Writing Data

In [4]:
url = "https://raw.githubusercontent.com/sarwansingh/Python/refs/heads/master/ClassExamples/data/iris.csv"
df = pd.read_csv(url, names = ['SepalLength', 'SepalWidth','PetalLength','PetalWidth','Species'], header=None)
df.head()

SepalLength  SepalWidth  PetalLength  PetalWidth      Species
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

### 3. Basic Data Exploration

In [5]:
print(df.info())
print(df.describe())
print(df.columns)
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   SepalLength  150 non-null    float64
 1   SepalWidth   150 non-null    float64
 2   PetalLength  150 non-null    float64
 3   PetalWidth   150 non-null    float64
 4   Species      150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
       SepalLength  SepalWidth  PetalLength  PetalWidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000
Index(['SepalLength', 'SepalWidth', 'Peta

### 4. Data Selection and Filtering

In [6]:
# Select  columns
print(df['Species'].head())

# conditional filtering
print(df[df['SepalLength'] > 5.0])

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object
     SepalLength  SepalWidth  PetalLength  PetalWidth         Species
0            5.1         3.5          1.4         0.2     Iris-setosa
5            5.4         3.9          1.7         0.4     Iris-setosa
10           5.4         3.7          1.5         0.2     Iris-setosa
14           5.8         4.0          1.2         0.2     Iris-setosa
15           5.7         4.4          1.5         0.4     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[118 rows x 5 columns]


In [7]:
# Multiple conditions
filtered = df[(df['Species'] == 'Iris-setosa') & (df['SepalWidth'] > 3.5)]
print(filtered)

    SepalLength  SepalWidth  PetalLength  PetalWidth      Species
4           5.0         3.6          1.4         0.2  Iris-setosa
5           5.4         3.9          1.7         0.4  Iris-setosa
10          5.4         3.7          1.5         0.2  Iris-setosa
14          5.8         4.0          1.2         0.2  Iris-setosa
15          5.7         4.4          1.5         0.4  Iris-setosa
16          5.4         3.9          1.3         0.4  Iris-setosa
18          5.7         3.8          1.7         0.3  Iris-setosa
19          5.1         3.8          1.5         0.3  Iris-setosa
21          5.1         3.7          1.5         0.4  Iris-setosa
22          4.6         3.6          1.0         0.2  Iris-setosa
32          5.2         4.1          1.5         0.1  Iris-setosa
33          5.5         4.2          1.4         0.2  Iris-setosa
44          5.1         3.8          1.9         0.4  Iris-setosa
46          5.1         3.8          1.6         0.2  Iris-setosa
48        

### 5. Adding and Modifying Columns

In [8]:
df['sepal_area'] = df.SepalLength * df.SepalWidth
df.head()

SepalLength  SepalWidth  PetalLength  PetalWidth      Species  sepal_area
0          5.1         3.5          1.4         0.2  Iris-setosa       17.85
1          4.9         3.0          1.4         0.2  Iris-setosa       14.70
2          4.7         3.2          1.3         0.2  Iris-setosa       15.04
3          4.6         3.1          1.5         0.2  Iris-setosa       14.26
4          5.0         3.6          1.4         0.2  Iris-setosa       18.00

In [9]:
df['petal_area'] = df.PetalLength * df.PetalWidth
df.head()

SepalLength  SepalWidth  PetalLength  PetalWidth      Species  sepal_area  \
0          5.1         3.5          1.4         0.2  Iris-setosa       17.85   
1          4.9         3.0          1.4         0.2  Iris-setosa       14.70   
2          4.7         3.2          1.3         0.2  Iris-setosa       15.04   
3          4.6         3.1          1.5         0.2  Iris-setosa       14.26   
4          5.0         3.6          1.4         0.2  Iris-setosa       18.00   

   petal_area  
0        0.28  
1        0.28  
2        0.26  
3        0.30  
4        0.28

### 6. Handling Missing Data

In [11]:
import numpy as np
# Introduce NaN
df.loc[0,'SepalLength'] = np.nan
df.isnull().sum()

SepalLength    1
SepalWidth     0
PetalLength    0
PetalWidth     0
Species        0
sepal_area     0
petal_area     0
dtype: int64

### 7. Sorting and Grouping

In [12]:
# Sort by Column
print(df.sort_values(by='SepalLength', ascending=False).head())


# Group by Species
grouped = df.groupby('Species')['SepalLength'].mean()
print(grouped)

     SepalLength  SepalWidth  PetalLength  PetalWidth         Species  \
131          7.9         3.8          6.4         2.0  Iris-virginica   
118          7.7         2.6          6.9         2.3  Iris-virginica   
117          7.7         3.8          6.7         2.2  Iris-virginica   
122          7.7         2.8          6.7         2.0  Iris-virginica   
135          7.7         3.0          6.1         2.3  Iris-virginica   

     sepal_area  petal_area  
131       30.02       12.80  
118       20.02       15.87  
117       29.26       14.74  
122       21.56       13.40  
135       23.10       14.03  
Species
Iris-setosa        5.004082
Iris-versicolor    5.936000
Iris-virginica     6.588000
Name: SepalLength, dtype: float64


### 8. Merging and Joining


In [13]:
df1 = pd.DataFrame({'ID':[1,2,3], 'Name': ['A','B','c']})
df2 = pd.DataFrame({'ID': [1,2,3], 'Score':[85,90,80]})
merged = pd.merge(df1,df2, on = 'ID')
print(merged)

   ID Name  Score
0   1    A     85
1   2    B     90
2   3    c     80


## Exercise

In [25]:
# Load a CSV dataset of your choice

df = pd.read_excel("adult_train.xlsx")
df

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income  
0              2174             0              40  United-States  <=50K  
1                 0             0              13  United-States  <=50K  
2                 0             0              40  United-States  <=50K  
3                 0             0              40  United-States  <=50K  
4                 0             0              40           Cuba  <=50K  
...             ...           ...             ...            ...    ...  
32556             0             0              38  United-States  <=50K  
32557             0             0              40  United-States   >50K  
32558             0             0              40  United-States  <=50K  
32559             0             0              20  United-States  <=50K  
32560         15024             0              40  United-States   >50K  

[32561 rows x 15 columns]

In [26]:
# Display top 10 Rows
df.head(10)

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   
5   37           Private  284582    Masters             14   
6   49           Private  160187        9th              5   
7   52  Self-emp-not-inc  209642    HS-grad              9   
8   31           Private   45781    Masters             14   
9   42           Private  159449  Bachelors             13   

          marital-status         occupation   relationship   race     sex  \
0          Never-married       Adm-clerical  Not-in-family  White    Male   
1     Married-civ-spouse    Exec-managerial        Husband  White    Male   
2               Divorced  Handlers-cleaners  Not-in-family  White    Male   
3     Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4     Married-civ-spouse     Prof-specialty           Wife  Black  Female   
5     Married-civ-spouse    Exec-managerial           Wife  White  Female   
6  Married-spouse-absent      Other-service  Not-in-family  Black  Female   
7     Married-civ-spouse    Exec-managerial        Husband  White    Male   
8          Never-married     Prof-specialty  Not-in-family  White  Female   
9     Married-civ-spouse    Exec-managerial        Husband  White    Male   

   capital-gain  capital-loss  hours-per-week native-country income  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K  
5             0             0              40  United-States  <=50K  
6             0             0              16        Jamaica  <=50K  
7             0             0              45  United-States   >50K  
8         14084             0              50  United-States   >50K  
9          5178             0              40  United-States   >50K

In [27]:
# Find the mean Age
avg_age = df.age.mean()
avg_age

np.float64(38.58164675532078)

In [28]:
# Count missing values
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

# Real-World Example: Iris Flower Dataset



## Step 1: Import Libraries and Load Dataset

In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

url = "https://raw.githubusercontent.com/sarwansingh/Python/refs/heads/master/ClassExamples/data/iris.csv"
df = pd.read_csv(url, names = ['SepalLength', "SepalWidth", "PetalLength", "PetalWidth", "Species"])
df

SepalLength  SepalWidth  PetalLength  PetalWidth         Species
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

## Step 2: Explore the Dataset

In [58]:
print("Shape of the dataset: ", df.shape)
print("\nColumns: ", df.columns.tolist())
print("\nData types\n", df.dtypes)
print("\nSummary statistics:\n", df.describe())

Shape of the dataset:  (150, 5)

Columns:  ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Species']

Data types
 SepalLength    float64
SepalWidth     float64
PetalLength    float64
PetalWidth     float64
Species         object
dtype: object

Summary statistics:
        SepalLength  SepalWidth  PetalLength  PetalWidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000


## Exercise 1

1.   Find how many unique Speices exist in the dataset.
2.   Display the count of each Species.



In [59]:
# Find how many unique species exist in the dataset
df.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [60]:
unique_val = df.Species.unique().tolist()

In [61]:
len(unique_val)

3

## Step 3: Data Selection and Filtering

In [62]:
sepal_length = df['SepalLength']
print("First 5 Sepal Length values: \n", sepal_length.head())

First 5 Sepal Length values: 
 0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: SepalLength, dtype: float64


In [63]:
selected = df[["SepalLength", "PetalLength", "Species"]]
selected.head()

SepalLength  PetalLength      Species
0          5.1          1.4  Iris-setosa
1          4.9          1.4  Iris-setosa
2          4.7          1.3  Iris-setosa
3          4.6          1.5  Iris-setosa
4          5.0          1.4  Iris-setosa

In [64]:
filtered = df[df['PetalLength'] > 1.5]
filtered.head()

SepalLength  SepalWidth  PetalLength  PetalWidth      Species
5           5.4         3.9          1.7         0.4  Iris-setosa
11          4.8         3.4          1.6         0.2  Iris-setosa
18          5.7         3.8          1.7         0.3  Iris-setosa
20          5.4         3.4          1.7         0.2  Iris-setosa
23          5.1         3.3          1.7         0.5  Iris-setosa

## Exercise 2

1.   Display all rows where sepal_width < 3.0
2.   Show only sepal_length and species columns.



## Step 4: Data Cleaning

In [65]:
df.head()

SepalLength  SepalWidth  PetalLength  PetalWidth      Species
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [66]:
print("Missing values\n", df.isnull().sum())

# Replace missing with mean (if any)
df.fillna(df.mean(numeric_only=True), inplace=True)

Missing values
 SepalLength    0
SepalWidth     0
PetalLength    0
PetalWidth     0
Species        0
dtype: int64


## Exercise 3


1.   Rename all columns back to lowercase.
2.   Drop Petal Width column and show first 5 rows.



In [67]:
# Rename all columns back to lowercase.
df.rename(columns = {'SepalLength':'sepallength',
'SepalWidth':'sepalwidth',
'PetalLength':'petallength',
'PetalWidth':'petalwidth',
'Species':'species'

},inplace = True)
df

sepallength  sepalwidth  petallength  petalwidth         species
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [68]:
# Drop petallength column and show first 5 rows.
df.drop('petallength',axis=1,inplace=True)
df.head(5)

sepallength  sepalwidth  petalwidth      species
0          5.1         3.5         0.2  Iris-setosa
1          4.9         3.0         0.2  Iris-setosa
2          4.7         3.2         0.2  Iris-setosa
3          4.6         3.1         0.2  Iris-setosa
4          5.0         3.6         0.2  Iris-setosa